/*
* format:
* USER_LOGIN_DOING
* */

// login
export const USER_LOGIN_BEFORE = 'USER_LOGIN_BEFORE'
export const USER_LOGIN_DOING = 'USER_LOGIN_DOING'
export const USER_LOGIN_AFTER = 'USER_LOGIN_AFTER'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

// main socket
export const SOCKET_CONNECT_BEFORT = 'SOCKET_CONNECT_BEFORE'
export const SOCKET_CONNECT_DOING = 'SOCKET_CONNECT_DOING'
export const SOCKET_CONNECT_FAIL = 'SOCKET_CONNECT_FAIL'
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS'